### PR TITLE
Document Fixing and Waves Implementation

### PR DESCRIPTION
**Pull request by CodexLink**
# Intro
Hello @djibe! I was interested in your continuation development of Daemonite/s Material Boostrap UI and I wanted to help you out because I feel the need of you, seeking help. Luckily, I was able to set up the repository in no time with bare minimum knowledge of setting things up. Anyway, about setting up, I will also include the instruction if I'm allowed but I'm gonna explain that later at the moment.

Anyway, upon inspecting your docs, I found a lot of things that need to be fixed. But since I have bare minimum knowledge about how 'this' docs structured (aside from knowing it was built from Jekyll) and also on web designing and development. I was only able to clean up some parts of the examples in an expansion panel were close buttons for chips are overlayed with material-icon fonts.

Also, since I found out you don't have waves effect for all parts. I was able to attach the library and try to add 'that' effect in Root Collapsible Items.

But since right now, I have the time to learn something about it. I'll **attempt** to do, fix *MOST* parts your docs so that you can focus building stuff alongside fixing it by yourself.

# Few Notes
* Since I really don't know how this node project works (I only know few for Jekyll btw), I didn't make any JS container file or put the code from any JS files. I was able to initialize the Waves library by Inline Script Tag. Which is located in footer.html
* I was unable to apply waves-effect in nav-toolbar from nav button toggle and history like a dropdown. It doesn't render but I put the class on the file.

# Instructions for Setting Up
I was luckily able to find ([This StackOverflow Question](https://stackoverflow.com/questions/49197652/expected-linebreaks-to-be-lf-but-found-crlf)). The solution helps me do executions of `npm run dist` and `npm run docs` without any errors. If you want me to add it in instructions, please tell me.

# What's next?
Since I was formal enough, soon, I want to contribute:
- Feature Specifics
- - [ ] Fix Title Format
- - [ ] Fix Stepper Icons
- - [ ] Fixed Navigation Bar with Waves Effect
- - [ ] Waves Effect on any Element That's Applicable
- - [ ] Apply Scrollspy and to All Docs.
- - [ ] Add Additional Information @ README.md
- Literally Documentation Sections
-- [ ] Coming Soon

I won't do all of those in one shot. I'll try to make time for this one since your efforts were so good I have to help even with bare knowledge about web development. Thanks and have a good day.

### CODE REVIEW

**Comment by CodexLink** [comment]
This commit https://github.com/djibe/material/pull/1/commits/d555decdbe526e8110cf00c370f56d9e0d84420d resolves from what I'm trying to apply waves effect at index.html. I never thought I did it from any other page except only on the homepage itself.

**Comment by CodexLink** [comment]
This commit broke TOC 61bef4c please do not merge. Check https://codexlink.github.io/material/ if you want to as all changes reflect there.

**Comment by CodexLink** [comment]
This commit (2c02411) fixes the duplicate container from where the TOC resides. 💯

**Comment by djibe** [comment]
Hi, thank you so much for your help.

You know, I'm no dev at all, I'm just a General practitionner ;-)

I'll look into it ASAP.

For the waves integration, I was thinking 
- to add it in a future release, to focus on BS 4.4.1 compatibility for now
- that I would integrate the plugin within material.js, and declare the plugin for all buttons and items that can be clicked. So you don't need to add waves-effect to every component.
What do you think ?

For Jekyll TOC : you can customize it from _config.yml

Thanks again, see you soon

**Comment by CodexLink** [comment]
Hey! Glad you replied :) Im gonna quote some of your replies and reply to it.
> For Jekyll TOC : you can customize it from _config.yml

I used different TOC rather than typical Jekyll-TOC because that was not updated *anymore*. They do working PROPERLY in *localhost*. Anyway, the one that I use is purely made in liquid. And that *resolves* your problem from the *right nav mirrors the content from the left* which you have said before [on this](https://github.com/Daemonite/material/issues/197).

> Hi, thank you so much for your help.
> You know, I'm no dev at all, I'm just a General practitionner ;-)

No problem man, I was just the same as you, but I really don't have enough knowledge but I'm interested in working with you because I liked how the components close enough to be as MDC (Material Design Components).

> to add it in a future release, to focus on BS 4.4.1 compatibility for now

> that I would integrate the plugin within material.js, and declare the plugin for all buttons and items that can be clicked. So you don't need to add waves-effect to every component.
What do you think ?

- I WAS really thinking about this one. And that would be really GREAT. I was about to do it, but I don't know-how. If you notice, the footer.html has its script initializing Waves. This indicates I was still reading how would you store codes.
- AND I was also don't have any idea where you store custom made scss. Because I fixed one lately about cards that has vertical buttons.


Anyway, look-out at my hosted one, which is forked of your repository. So that you can see changes without forking mine. Here is the [link](https://github.com/CodexLink/material).

Also, I'm ready for you to help out if you want to merge my work with yours so that we're updated.

And lastly, I want to include my instructions on how to work with your repo, would you mind? Anyway thanks, I would still commit and you can see some changes sooner or later.

**Comment by CodexLink** [comment]
Closed due to files kept being changed in a matter of time.

**Comment by djibe** [comment]
I fixed the steppers in a different manner today.
They are available on Master branch now.

I'll fix card-actions soon.
I did some work on documentation for Material buttons last night.

Enjoy ;-)

**Comment by CodexLink** [comment]
> I fixed the steppers in a different manner today.
> They are available on Master branch now.
> 
> I'll fix card-actions soon.
> I did some work on documentation for Material buttons last night.
> 
> Enjoy ;-)

That's awesome :) Right on time where I'm about to use your repo work (.css and .js) :)

**Comment by CodexLink** [comment]
And also yeah, I don't know if you fixed this one in master branch yet but in gh-pages branch, your stepper icons is still not yet centered properly. Please lookup this commit that I did here recently, https://github.com/djibe/material/pull/1/commits/5f14ddd527a9cbdc54fb1fa40a88a175399169f7 thanks. :) I might do git pull to and rerun everything to see if the stepper center icon issue is fixed.

**Comment by djibe** [comment]
Yep doc is still not updated ;-)
Tonight I hope

**Comment by djibe** [comment]
Done. What do you think of the buttons ?

**Comment by CodexLink** [comment]
> Done. What do you think of the buttons ?

Sorry late reply, what branch should I look at it? In gh-branch or master?

I assume you're asking me the buttons in gh-pages branch. They look really nice and fine now, really matches the MDC itself. I tried comparing them differently on how they react, and they matched :) So nice one.

**Comment by djibe** [comment]
Yes the doc https://djibe.github.io/material/docs/4.4/material/buttons/

However some buttons still don't have correct hover effect (light ones). I'm on it ;-)

**Comment by CodexLink** [comment]
> Yes the doc https://djibe.github.io/material/docs/4.4/material/buttons/
> 
> However some buttons still don't have correct hover effect (light ones). I'm on it ;-)

Oh yeah, I didn't saw that, you have to make the hover effect a bit darker, because the ones that we have right now is a bit light.

**Comment by djibe** [comment]
New cards documentation : https://djibe.github.io/material/docs/4.4/material/cards/

**Comment by CodexLink** [comment]
> New cards documentation: https://djibe.github.io/material/docs/4.4/material/cards/

Okay, they're really good now. One thing that I noticed that the vertical button space in the card is still not fixed. I have this commit https://github.com/djibe/material/pull/1/commits/1729a64aeb69dda098ad9d1fbcb7e478ff375647 which fixed that issue, would you mind or should I pull request about it? I wanna help though :)  

If you want me to show how it looks like and how I did, I can provide screenshots and info at 6pm UTC +8 (PHT)

**Comment by djibe** [comment]
You help a lot !

I deleted those vertical buttons in cards as they no longer appear in Material guidelines.

**Comment by CodexLink** [comment]
@djibe Thanks. I though you will still reconsider those despite compatibility (as I'm aware it really doesn't exist anymore in the material guidelines)

**Comment by djibe** [comment]
OK I'll reitroduce it and change the doc.
Thx

**Comment by CodexLink** [comment]
> OK I'll reitroduce it and change the doc.
> Thx

Hey @djibe , I didn't say it to reproduce it though. I just thought about it in the first place of why it exists when you said it does not in material guidelines anymore so I guess don't? :)

**Comment by djibe** [comment]
Brand new icon buttons
https://djibe.github.io/material/docs/4.4/material/buttons/#icon-buttons

Fixed card-columns
https://djibe.github.io/material/docs/4.4/material/cards/

Fixed dialog buttons too.

Thx for your help.

**Comment by CodexLink** [comment]
> Brand new icon buttons
> https://djibe.github.io/material/docs/4.4/material/buttons/#icon-buttons
> 
> Fixed card-columns
> https://djibe.github.io/material/docs/4.4/material/cards/
> 
> Fixed dialog buttons too.
> 
> Thx for your help.

No problem. Looking forward to this project :)

**Pull request closed without merging**
